samples: "config/samples.tsv"
units: "config/units.tsv"
general:
  outdir: "/scratch/shatira/batch4/"
  benchmark: 1
  genome_preparation:
    threads: 12
    extra: ""
    aligner: bowtie2
# these steps are user defined and will condition which part of the pipeline is executed and which output files the user requests
steps:
  # minimal vs full run
    subsample:
      activated: 'False'
  # whether to preprocess raw data or not
    trimming:
      activated: 'True'
  # whether to generate quality reports or not
    quality:
      activated: 'True'
  # whether to perform bisulfite conversion on genome and index it (preparation)
    genome_preparation:
      activated: 'True'
  # whether to perform methylation extraction
    methylation_extraction_bismark:
      activated: 'True'
  # whether to perform differential methylation calling
    methylation_calling:
      activated: 'True'

resources:
  ref:
    genome: "/scratch/shatira/genome/190502MalusdomesticaV4chrchrs.fa"
    #Directory containing a fasta file with the DNA sequence of the organism sutided.
  adapters: "/scratch/shatira/resources/adapters"

Rossa:
  params:
    trimmomatic-pe:
      trimmer: "ILLUMINACLIP"
      trimmer-options: "2:30:10:2:keepBothReads LEADING:3 TRAILING:3 MINLEN:100"
      threads: 32
      extra: ""
    seqtk:
      seed: 100
      size: 10000
      extra: ""
    bismark:
      aligner: bowtie2 #bowtie2/hisat2
      aligner_options: ""
      instances: 8 
      score_min: L,0,-0.6
      N: 1
      L: 32
      extra: ""
      bool_flags: 
        nucleotide_coverage: "True"
        no_dovetail: "False"
        non_directional: "False"
    deduplicate:
      extra: "" # see deduplicate_bismark documentation
    methylation_extraction:
      bool_flags:
        bedGraph: "True"
        CX:  "True"
        cytosine_report:  "True"
        comprehensive:  "True"
        split_by_chromosome: "False"
      extra: ""
    fastqc:
      extra : ""
    multiqc:
      extra : ""
Gala:
  params:
    trimmomatic-pe:
      trimmer: "ILLUMINACLIP"
      trimmer-options: "2:30:10:2:keepBothReads LEADING:3 TRAILING:3 MINLEN:100"
      threads: 32
      extra: ""
    seqtk:
      seed: 100
      size: 10000
      extra: ""
    bismark:
      aligner: bowtie2 #bowtie2/hisat2
      aligner_options: ""
      instances: 8 
      score_min: L,0,-0.7
      N: 0
      L: 20
      extra: ""
      bool_flags: 
        nucleotide_coverage: "True"
        no_dovetail: "False"
        non_directional: "False"
    deduplicate:
      extra: "" # see deduplicate_bismark documentation
    methylation_extraction:
      bool_flags:
        bedGraph: "True"
        CX:  "True"
        cytosine_report:  "True"
        comprehensive:  "True"
        split_by_chromosome: "False"
      extra: ""
    fastqc:
      extra : ""
    multiqc:
      extra : ""